version: "3"
services:
  database:
    container_name: postgres-java
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    expose:
      - 5432
    network_mode: host
